AllCops:
  Exclude:
    - 'bin/**/*'
    - 'test/**/*'
    - 'lib/world/MA_geo.rb'
    - 'lib/records/lookup.rb'
    - 'lib/records/shr_mapping.rb' # ignored because generated code
    - 'lib/tasks/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Metrics:
  Enabled: false

Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false