synthea:
  start_date: <%= Time.now - 100.years %>
  end_date: <%= Time.now - 1.day %>
  population: 
    area: 0.05
    birth_variance: 0.01
    daily_births_per_square_mile: <%= (ma_births_per_year = 73000.0)/(ma_square_miles=10554.0)/365.0 %>
  schedule:
    variance: 0.1

